In [ ]:
import numpy as np


In [3]:
import nummpy as np

ModuleNotFoundError: No module named 'nummpy'

In [4]:
import numpy at np

SyntaxError: invalid syntax (ipython-input-2919232410.py, line 1)

In [5]:
import numpy as nt

In [6]:
numbers = np.array([1, 2, 3, 4, 5])

In [7]:
prind("평균:", np.mean(numbers))

NameError: name 'prind' is not defined

In [8]:
print("평균:", np.mean([1, 2,3, 4, 5]]))


SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (ipython-input-3899927045.py, line 1)

In [9]:
print("평균:", np.mean(1, 2, 3, 4, 5))

AxisError: axis 2 is out of bounds for array of dimension 0

In [10]:
print( np.mean(numbers))


3.0


In [15]:
1 zeronumbers=np.zeroset

SyntaxError: invalid syntax (ipython-input-3491542996.py, line 1)

In [18]:
numbers[2]

np.int64(3)

In [20]:
numbers [4]

np.int64(5)

In [21]:
matrix = np.array([[1, 2], [3, 4]])
print("행렬:\n", matrix)


행렬:
 [[1 2]
 [3 4]]


In [25]:
matrix=[1,0]

In [26]:
import pandas as pd


In [27]:
students = pd.DataFrame({
'이름': ['김철수', '이영희', '박민수'],
'수학': [85, 92, 78],
'영어': [78, 85, 90]


SyntaxError: incomplete input (ipython-input-3264750352.py, line 4)

In [28]:
print(students)


NameError: name 'students' is not defined

In [30]:
students = pd.DataFrame({
'이름': ['김철수', '이영희', '박민수'],
'수학': [85, 92, 78],
'영어': [78, 85, 90]
})

In [31]:
print(students)

    이름  수학  영어
0  김철수  85  78
1  이영희  92  85
2  박민수  78  90


In [32]:
1 numbers 3

SyntaxError: invalid syntax (ipython-input-3439036942.py, line 1)

In [39]:
print (students [1, 3])

KeyError: (1, 3)

In [40]:
import matplotlib.pyplot as plt
# 한글 폰트 설정 (한글 깨짐 방지)
plt.rcParams['font.family'] = 'Malgun Gothic' # Windows
plt.rcParams['axes.unicode_minus'] = False
# 간단한 그래프 그리기
x = [1, 2, 3, 4, 5]
y = [2, 4, 6, 8, 10]
plt.figure(figsize=(8, 5))
plt.plot(x, y, 'bo-', label='데이터')
plt.title('간단한 그래프 예제')
plt.xlabel('X 값')
plt.ylabel('Y 값')
plt.legend()
3. 첫 번째 머신러닝 모델 만들기
이제 실제로 간단한 AI 모델을 만들어보겠습니다. 공부 시간과 시험 점수 사이의 관계를 찾는 모델입니다.
선형 회귀 - 가장 기본적인 예측 모델
plt.grid(True, alpha=0.3)
plt.show()

SyntaxError: invalid syntax (ipython-input-1562787421.py, line 14)

In [41]:
plt.rcParams['font.family'] = 'Malgun Gothic'

NameError: name 'plt' is not defined

In [42]:
plt.figure(figsize=(8, 5))
plt.plot(x, y, 'bo-', label='데이터')


NameError: name 'plt' is not defined

In [43]:
x = [1, 2, 3, 4, 5]
y = [2, 4, 6, 8, 10]


In [44]:
plt.plot(x, y, 'bo-', label='데이터')
plt.title('간단한 그래프 예제')


NameError: name 'plt' is not defined

In [45]:
import numpy as np


In [46]:
import matplotlib.pyplot as plt


In [47]:
from sklearn.linear_model import LinearRegression


In [48]:
공부시간 = np.array([1, 2, 3, 4, 5, 6, 7, 8]).reshape(-1, 1)

In [49]:
시험점수 = np.array([50, 55, 65, 70, 75, 85, 90, 95])


In [64]:
for i in range(len(공부시간)):
     print(f"공부시간: {공부시간[i][0]}시간 → 점수: {시험점수[i]}점")

공부시간: 1시간 → 점수: 50점
공부시간: 2시간 → 점수: 55점
공부시간: 3시간 → 점수: 65점
공부시간: 4시간 → 점수: 70점
공부시간: 5시간 → 점수: 75점
공부시간: 6시간 → 점수: 85점
공부시간: 7시간 → 점수: 90점
공부시간: 8시간 → 점수: 95점


In [66]:
1 model= LinearRegression()
2 model.fit (공부시간, 시험점수)

LinearRegression()

In [67]:
np.array([6.5])

array([6.5])

In [69]:
model.predict(np.array([6.5]).reshape(-1, 1))

array([86.33928571])

In [70]:
np.array([100])

array([100])

In [73]:
model.predict(np.array(100).reshape (-1,1))

array([704.10714286])